"use client";

import Link from "next/link";
import { StarsBackground } from "@/components/stars-background";
import { RocketIcon } from "@/components/rocket-icon";
import { Footer } from "@/components/footer";

const LAST_UPDATED = "March 9, 2026";

const SECTIONS = [
  {
    icon: "🚀",
    title: "Submissions",
    color: "var(--neon-pink)",
    borderColor: "rgba(255, 45, 120, 0.25)",
    glowColor: "rgba(255, 45, 120, 0.12)",
    glowClass: "neon-glow-pink-sm",
    paragraphs: [
      "By submitting a product to Launchpad.today, you grant us the right to display, score, and rank your product on our platform. This includes showing your product name, tagline, description, URL, category, and AI-generated scores.",
      "You confirm that you have the authority to submit the product and that all information provided is accurate. If you're submitting someone else's product, make sure you have their permission.",
    ],
  },
  {
    icon: "🤖",
    title: "AI Scores & Rankings",
    color: "var(--neon-cyan)",
    borderColor: "rgba(0, 240, 255, 0.25)",
    glowColor: "rgba(0, 240, 255, 0.12)",
    glowClass: "neon-glow-cyan-sm",
    paragraphs: [
      "All scores on Launchpad.today are generated by AI algorithms. They're not endorsements, investment recommendations, or predictions of success. A high score doesn't mean we think you should quit your job and go all-in. A low score doesn't mean your product is bad.",
      "Scores reflect an algorithmic assessment at a specific point in time based on publicly available information. They can and will change as our AI models improve.",
      "We provide no warranty on the accuracy, completeness, or reliability of any score or ranking.",
    ],
  },
  {
    icon: "⚖️",
    title: "Content Moderation",
    color: "var(--neon-purple)",
    borderColor: "rgba(176, 38, 255, 0.25)",
    glowColor: "rgba(176, 38, 255, 0.12)",
    glowClass: "neon-glow-purple-sm",
    paragraphs: [
      "We reserve the right to remove any submission at any time, for any reason. This includes but isn't limited to: spam, misleading information, offensive content, or products that violate applicable laws.",
      "If your submission gets removed, we'll try to let you know why. But we're not obligated to provide an explanation or reinstate removed content.",
    ],
  },
  {
    icon: "🎯",
    title: "User Conduct",
    color: "var(--neon-yellow)",
    borderColor: "rgba(255, 230, 0, 0.25)",
    glowColor: "rgba(255, 230, 0, 0.12)",
    glowClass: "neon-glow-yellow-sm",
    paragraphs: [
      "Don't submit fake products. Don't submit the same product multiple times to game the system. Don't use bots or automated tools to manipulate upvotes or rankings.",
      "Don't submit products that are illegal, harmful, or designed to deceive users. We're building a platform for real products built by real people.",
      "Violating these rules may result in your submission being removed and your ability to submit being revoked.",
    ],
  },
  {
    icon: "📋",
    title: "Intellectual Property",
    color: "var(--neon-green)",
    borderColor: "rgba(57, 255, 20, 0.25)",
    glowColor: "rgba(57, 255, 20, 0.12)",
    glowClass: "neon-glow-green-sm",
    paragraphs: [
      "You retain all rights to your product and brand. Submitting to Launchpad.today doesn't transfer any ownership.",
      "The Launchpad.today name, design, AI scoring methodology, and site content are our intellectual property. Don't scrape our data, clone our scoring system, or use our brand without permission.",
    ],
  },
  {
    icon: "⚡",
    title: "Limitation of Liability",
    color: "var(--neon-pink)",
    borderColor: "rgba(255, 45, 120, 0.25)",
    glowColor: "rgba(255, 45, 120, 0.12)",
    glowClass: "neon-glow-pink-sm",
    paragraphs: [
      "Launchpad.today is provided as-is. We make no guarantees about uptime, score accuracy, or the platform's availability.",
      "We're not liable for any decisions you make based on scores or rankings displayed on the platform. Use your own judgment.",
    ],
  },
  {
    icon: "🔄",
    title: "Changes to Terms",
    color: "var(--neon-cyan)",
    borderColor: "rgba(0, 240, 255, 0.25)",
    glowColor: "rgba(0, 240, 255, 0.12)",
    glowClass: "neon-glow-cyan-sm",
    paragraphs: [
      "We may update these terms as the platform evolves. When we do, we'll update the date at the top of this page. Continued use of Launchpad.today after changes means you accept the new terms.",
    ],
  },
];

export function TermsContent() {
  return (
    <div className="min-h-screen grid-bg horizon-gradient relative">
      <StarsBackground />

      {/* Header */}
      <header className="relative z-10 border-b border-white/[0.06]">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <div className="animate-rocket-float">
              <RocketIcon size={36} flame={true} />
            </div>
            <div>
              <h1
                className="text-lg sm:text-xl font-bold tracking-wider uppercase"
                style={{ fontFamily: "'Orbitron', sans-serif" }}
              >
                <span style={{ color: "var(--neon-cyan)" }}>Launch</span>
                <span style={{ color: "var(--neon-pink)" }}>pad</span>
                <span className="text-white/40">.today</span>
              </h1>
            </div>
          </Link>

          <Link
            href="/"
            className="submit-btn px-4 py-2 rounded text-xs sm:text-sm text-white inline-block"
          >
            Back to Launches
          </Link>
        </div>
      </header>

      {/* Main content */}
      <main className="relative z-10 max-w-3xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
        {/* Page heading */}
        <section className="text-center mb-12 sm:mb-16">
          <div
            className="text-xs uppercase tracking-[6px] mb-4"
            style={{
              fontFamily: "'Orbitron', sans-serif",
              color: "var(--neon-pink)",
            }}
          >
            <span className="neon-glow-pink-sm">Legal Transmission</span>
          </div>
          <h2
            className="text-3xl sm:text-4xl font-black tracking-wider uppercase mb-4"
            style={{ fontFamily: "'Orbitron', sans-serif" }}
          >
            <span className="chrome-text">Terms of</span>{" "}
            <span style={{ color: "var(--neon-pink)" }} className="neon-glow-pink-sm">
              Service
            </span>
          </h2>
          <div className="retro-divider max-w-xs mx-auto mb-4" />
          <p className="text-xs text-white/30 uppercase tracking-widest">
            Last updated: {LAST_UPDATED}
          </p>
        </section>

        {/* Intro */}
        <section className="mb-10">
          <div className="retro-card rounded-2xl p-6 sm:p-8">
            <p className="text-sm text-white/60 leading-relaxed">
              By using Launchpad.today, you're agreeing to these terms. They're written in plain
              language because nobody reads legalese and we'd rather you actually understand what
              you're signing up for.
            </p>
          </div>
        </section>

        {/* Sections */}
        <div className="space-y-6">
          {SECTIONS.map((section) => (
            <section key={section.title}>
              <div className="retro-card rounded-xl p-6 sm:p-8">
                <div className="flex items-center gap-3 mb-5">
                  <div
                    className="w-10 h-10 rounded-lg flex items-center justify-center text-lg shrink-0"
                    style={{
                      border: `1px solid ${section.borderColor}`,
                      boxShadow: `0 0 12px ${section.glowColor}`,
                      background: "rgba(10, 10, 25, 0.8)",
                    }}
                  >
                    {section.icon}
                  </div>
                  <h3
                    className={`text-sm sm:text-base font-bold tracking-wider uppercase ${section.glowClass}`}
                    style={{
                      fontFamily: "'Orbitron', sans-serif",
                      color: section.color,
                    }}
                  >
                    {section.title}
                  </h3>
                </div>

                <div className="space-y-3 text-sm text-white/55 leading-relaxed">
                  {section.paragraphs.map((p, i) => (
                    <p key={i}>{p}</p>
                  ))}
                </div>
              </div>
            </section>
          ))}
        </div>

        {/* Contact */}
        <section className="mt-10">
          <div
            className="retro-card rounded-2xl p-6 sm:p-8 text-center"
            style={{
              borderColor: "rgba(255, 45, 120, 0.15)",
              background: "rgba(15, 10, 25, 0.9)",
            }}
          >
            <h3
              className="text-sm font-bold tracking-wider uppercase neon-glow-pink-sm mb-3"
              style={{ fontFamily: "'Orbitron', sans-serif", color: "var(--neon-pink)" }}
            >
              Questions?
            </h3>
            <p className="text-sm text-white/45 mb-4">
              If something here doesn't make sense, ask us. We'd rather explain it than have you
              guess.
            </p>
            <a
              href="mailto:hello@launchpad.today"
              className="submit-btn px-6 py-2.5 rounded-lg text-sm text-white inline-block"
            >
              hello@launchpad.today
            </a>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
